### ISSUE TITLE
[1.20.1] Instant Crashing when opening video settings

### ISSUE THREAD

**Issue by NovaViper** [ThinkingStudios/textrues-rubidium-options#11]
Hey I'm using the latest 1.20.1 version of this mod and whenever I open up the video settings menu, the game instantly crashes with this [error log](https://pastebin.com/C0ZSTgLd)

System Info:
OS: NixOS 23.11-unstable
Launcher: Prism Launcher 7.2
Java 1.17
Minecraft Version: 1.20.1
Rubidium v0.6.5
Rubidium Extra v0.4.20+m1.20-build.91
Rubidium Dynamic Lights v1.20.1_v1.5.0

**Comment by TexBlock** [comment]
Please use the latest Rubidium & Rubidium Extra.

**Comment by NovaViper** [comment]
> Please use the latest Rubidium & Rubidium Extra.

Issue is though, the lastest versions of both mods are completely broken, I can't run v0.7.0 or 0.7.0a of Rubidium because it just causes the game to instantly crash and updating Rubidium Extras to 1.5.0-build98 also makes the game crash.

**Comment by TexBlock** [comment]
> > Please use the latest Rubidium & Rubidium Extra.
> 
> Issue is though, the lastest versions of both mods are completely broken, I can't run v0.7.0 or 0.7.0a of Rubidium because it just causes the game to instantly crash and updating Rubidium Extras to 1.5.0-build98 also makes the game crash.

ok, i will backport to rubidium 0.6.5 in somedays

**Comment by TexBlock** [comment]
@NovaViper Please use this version: [1.0.0+23H1+Rb0.6.5-mc1.20.1](https://modrinth.com/mod/textrues-rubidium-options/version/1.0.0+23H1+Rb0.6.5-mc1.20.1)
