### ISSUE TITLE
Texture Colours turn Weird as soon as i use this mod

### ISSUE THREAD

**Issue by KitsuYona** [ThinkingStudios/textrues-rubidium-options#13]
Hello there,
I struggled for some time now, to get to the ground of a big texture "Problem" i had in Minecraft...
I'm Using a whole Bunch of Mods and had the Problem that, for example, the Grass Textures in many Biomes turned Blue all of a sudden... (like visible here: there are 4 Biomes.... Seasonal Orchard(the one with the bluest Grass)/Highlands(where the Pumpkins(orange Spots) are)/Forest(above the Highlands...in the middle-right part) and the Plains.... (top right part)
![image](https://github.com/ThinkingStudios/textrues-rubidium-options/assets/148748248/a2c5dfca-c3bc-4a7d-8bdb-34fbb7021ecd)

 And Water inside of Cauldrons turned Brown.... 
![Bild_2023-10-23_090128806](https://github.com/ThinkingStudios/textrues-rubidium-options/assets/148748248/22ceca5c-f41f-403f-9241-b89d73776a14)

after Many trial and Errors, i Finally found out that it is exactly the Textrue Rubidium Options Mod that is causing this Problem....

Is there any Possible Solution for this? or just the Phrase "Just don't use the Mod"?

**Comment by Kasualix** [comment]
In no way do I think this is a problem that TRO can cause, are you sure?

**Comment by KitsuYona** [comment]
yes I am Sure

I even created a New Modpack and only kopied the Mods ... no Configs, Saves ect.. 
And the The Textures only got to normal again when i deactivated all rubidium and Magnesium related Mods (what where almoste the last ones, because i didn't think either that these are the onse causing this)... then i tried activating all Mods leaving out only the Magnesium + Rubidium(and related) and the Textures still kept their normal look... even when activating magnesium and Rubidium,.... only when i got to the Textrues Rubidium Options Mod got the Textures weird again....

and i still don't know what of the Mod could even cause this

**Comment by TexBlock** [comment]
I don't think it's a TRO issue, it could be other mods causing this problem.
