### ISSUE TITLE
UI错误

### ISSUE THREAD

**Issue by wsxiya** [ThinkingStudios/textrues-rubidium-options#14]
在视频设置里，具有右侧滑动条的界面时，会出现错误，forge版本47.1.3，游戏版本为1.20.1，模组版本为1.0.4

![EK3$JAL5WX0 4`2YTSM(6AX](https://github.com/ThinkingStudios/textrues-rubidium-options/assets/114494454/5579b5f7-5364-47c9-8553-5227625ba151)

**Comment by TexBlock** [comment]
After testing, this mod is not installed with `rubidium` alone, this problem occurs with `rubidium extra`.
经测试，此模组单独和`rubidium`一起安装不会出现此问题，这个问题和`rubidium extra`安装时才会发生。
