### ISSUE TITLE
[Log] Mixin config reeses_sodium_options.mixins.json does not specify "minVersion" property

### ISSUE THREAD

**Issue by Lucky-56** [ThinkingStudios/textrues-rubidium-options#2]
Just annoying in log

**Forge:** 43.1.47
**Mod Version:** 1.0.3

**Comment by TexBlock** [comment]
Fixed in version [1.19.x-v1.0.3-Hotfix](https://github.com/TexTrueStudio/ReesesSodiumOptions-Forge/releases/tag/mc1.19.x-forge-v1.0.3-Hotfix)
