### ISSUE TITLE
1.19.3 is really support?

### ISSUE THREAD

**Issue by 7934345** [ThinkingStudios/textrues-rubidium-options#3]
Here is the crash log:
https://gist.github.com/7934345/8918312689f29af41629f26fa03ad013

Just open video setting and CTD

and disable textrues_rubidium_options-1.0.3-Hotfix-mc1.19.2.jar, everything goes well.

**Comment by TexBlock** [comment]
目前TRO尚未支持1.19.3

你倒是提醒我该更新1.19.3了（

**Comment by 7934345** [comment]
![image](https://user-images.githubusercontent.com/2296368/210323480-7402d8ee-e888-40a0-9f6f-3d0f6c2c7210.png)
好吧 那么我被 client 骗了 或者 你标注的version 有问题， anyway thx for all.

**Comment by TexBlock** [comment]
貌似版本标错了，我现在改回来（
然后1.19.3今天应该会移植完发布（？

**Comment by TexBlock** [comment]
1.19.3已发布
