### ISSUE TITLE
bug: overlapping elements in settings menu on 1.19.2

### ISSUE THREAD

**Issue by MichaelHillcox** [ThinkingStudios/textrues-rubidium-options#5]
Hi, forwarding this issue from our Modpacks Repo. (https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2902)

## The Bug

https://user-images.githubusercontent.com/66274985/229901015-6875df17-1fe3-446a-9235-66bfc08152a6.png

As you can see, in the top right, the two elements would appear to overlap.

Many thanks.

**Comment by TexBlock** [comment]
Sorry, just saw it now. It looks like something isn't working and I'm trying to fix it now.

**Comment by TexBlock** [comment]
fixed in v1.0.5

I will upload on curseforge & modrinth

**Comment by TexBlock** [comment]
uploaded
